
spring:
  mail:
    host: smtp-mail.outlook.com
    username: timonwin@outlook.com
    password: rvpxsfxvxqaitnmd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true